[package]
name = "openbook-crank"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "openbook_crank"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
localnet = []
devnet = ["anchor-spl/devnet"]

[profile.release]
overflow-checks = true

[dependencies]
anchor-spl = { version = "0.26.0", features = ["dex"] }
anchor-lang = "0.26.0"
clockwork-sdk = { version = "1.4.0" }
safe-transmute = "0.11.0"
